github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/whop-video-downloader",
"https://chromewebstore.google.com/detail/whop-video-downloader/obiiijgnmblffcopbdfpdlmbdkgmblgf",
"https://extensions.serp.co/extensions/serp/whop-video-downloader/",
"",
]
