github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/whop-video-downloader",
"https://serp.co/products/whop-video-downloader/reviews/",
"https://chromewebstore.google.com/detail/whop-video-downloader/obiiijgnmblffcopbdfpdlmbdkgmblgf",
"https://whop.com/serp-downloaders/whop-video-downloader/"
]
