github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://store.serp.co/product-details/product/whop-video-downloader",
"https://apps.serp.co/whop-video-downloader",
"https://serp.co/products/whop-video-downloader/reviews/",
"https://chromewebstore.google.com/detail/whop-video-downloader/obiiijgnmblffcopbdfpdlmbdkgmblgf"
]
