name: Update Gist URL

on:
  workflow_dispatch:
    inputs:
      gist_url:
        description: 'GitHub Gist URL to add to readme.json'
        required: true
        type: string
        default: ''

jobs:
  call-workflow:
    uses: serpapps/.github/.github/workflows/update-gist-url.yml@main
    with:
      gist_url: ${{ github.event.inputs.gist_url }}
